services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - "discovery.type=single-node"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"