---
- name: Deploy
  hosts: localhost
  tasks:

  # TODO: Stat file first to see if exists
  - name: Decrypt local secrets.env
    ansible.builtin.command: >
      ansible-vault decrypt --vault-password-file= vault_password ../docker/secrets.env.local
      --output ../docker.secrets.env
