---
- name: Deploy
  hosts: all
  tasks:

  - name: Ensure local data directories
    become: yes
    ansible.builtin.file:
      path: "{{ item.path | template }}"
      owner: "{{ item.owner | default(omit) | template }}"
      group: "{{ item.group | default(omit) | template }}"
      state: directory
      mode: "{{ item.mode | default('755') | template }}"
    loop:
      - '{{ data_dirs | dict2items }}'
    when: item.pull | default(false)
    delegate_to: localhost
