version: '3.7'

services:
  backend:
    image: node:16
    volumes:
      - ../backend:/usr/src/app
    build: 
      context: ../backend
      dockerfile: Dockerfile
  frontend:
    image: docker.ub.gu.se/db-list-frontend:${GIT_REVISION}