version: '3.7'

services:
  backend:
    container_name: db-list-backend
    ports:
      - '${BACKEND_HOST_PORT}:5000'
  frontend:
    container_name: db-list-frontend
    environment:
      VUE_APP_ALERT_URL: "${ALERT_URL}"
    ports:
      - ${FRONTEND_HOST_PORT}:8080
networks:
    default:
        name: db-list-net