version: '3.7'
services:
  frontend-admin:
    restart: always
    ports:
      - ${FRONTEND_ADMIN_HOST_PORT}:80
  backend-admin:
    restart: always
    env_file:
      - secrets.env
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
    ports:
      - "${BACKEND_ADMIN_HOST_PORT}:4000"
  frontend-nuxt:
    restart: always
    ports:
      - ${FRONTEND_HOST_PORT}:3000
  backend:
    restart: always
  db:
    restart: always
  elasticsearch:
    restart: always
    volumes:
      - ${ELASTICSEARCH_DATA_PATH}:/usr/share/elasticsearch/data
