version: '3.7'

services:
  elasticsearch: 
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
  backend: 
    volumes:
      - "${BACKEND_REPO}:/release/backend"
  frontend:
    image: ebiven/vue-cli
    environment:
      VUE_APP_API_BASE_URL: "${DB_LIST_BACKEND_URL}"
      VUE_APP_ALERT_URL: "${DB_LIST_ALERT_URL}"
    volumes:
      - ../frontend:/code
    ports:
      - ${FRONTEND_HOST_PORT}:8080
    command: ["npm", "run", "serve"] 