version: "3.7"

services:
  frontend-admin:
    image: docker.ub.gu.se/databaser-frontend-admin:${GIT_REVISION}${PLATFORM}
    environment:
      DATABASER_BACKEND_ADMIN_URL: "${DATABASER_BACKEND_ADMIN_URL}"
  frontend-nuxt-3:
    image: docker.ub.gu.se/databaser-frontend-nuxt-3:${GIT_REVISION}${PLATFORM}
    environment:
      NUXT_API_BASE_URL: "${DATABASER_BACKEND_URL}"
  backend:
    image: docker.ub.gu.se/databaser-backend:${GIT_REVISION}${PLATFORM}
    environment:
      ELASTIC_SEARCH_URL: "${ELASTIC_SEARCH_URL}"
      ALERT_MESSAGE_FILE_PATH: "${ALERT_MESSAGE_FILE_PATH}"
    restart: always
    volumes:
      - "${HOST_ALERT_MESSAGE_FILE_PATH}:${ALERT_MESSAGE_FILE_PATH}"
  backend-admin:
    image: docker.ub.gu.se/databaser-backend-admin:${GIT_REVISION}${PLATFORM}
    environment:
      ELASTIC_SEARCH_URL: "${ELASTIC_SEARCH_URL}"
      ALERT_MESSAGE_FILE_PATH: "${ALERT_MESSAGE_FILE_PATH}"
    restart: always
    volumes:
      - "${HOST_ALERT_MESSAGE_FILE_PATH}:${ALERT_MESSAGE_FILE_PATH}"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${DB_INIT_PATH}:/docker-entrypoint-initdb.d"
    restart: always
  elasticsearch:
    image: docker.ub.gu.se/databaser-elasticsearch:${GIT_REVISION}${PLATFORM}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
