version: '3.7'

services:
  db:
    ports:
      - "127.0.0.1:5433:5432"
  backend-admin:
    volumes:
      - ../backend-admin:/release/backend-admin/
  backend:
    volumes:
      - ../backend:/release/backend/
  elasticsearch: 
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
  frontend:
    image: node:16
    environment:
      VUE_APP_API_BASE_URL: "${DB_LIST_BACKEND_URL}"
      VUE_APP_ALERT_URL: "${DB_LIST_ALERT_URL}"
    volumes:
      - ../frontend:/code
    ports:
      - ${FRONTEND_HOST_PORT}:8080
    command: "bash -c 'npm install && npm run serve'"
    working_dir: /code 