version: "3"

services:
  frontend:
    image: docker.ub.gu.se/minalan-frontend:${GIT_REVISION}
    ports:
      - ${FRONTEND_HOST_PORT}:80
    environment:
      MYLOANS_BACKEND_URL: "${MYLOANS_BACKEND_URL}"
    restart: always