version: '3.7'
services:
  backend:
    restart: always
  backend-admin:
    restart: always
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
  db:
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data/pgdata
  frontend-nuxt:
    restart: always
  frontend-admin:
    restart: always
  elasticsearch:
    restart: always
    volumes:
      - ${ELASTICSEARCH_DATA_PATH}:/usr/share/elasticsearch/data
