version: '3.7'

services:
  backend:
    container_name: db-list-backend
    #image: docker.ub.gu.se/minalan-backend:${GIT_REVISION}
    image: docker.ub.gu.se/db-list-backend:${GIT_REVISION}
    ports:
      - "${BACKEND_HOST_PORT}:4000"
    environment:
      ELASTIC_SEARCH_URL: "${ELASTIC_SEARCH_URL}"
    #  ALERT_URL: "${ALERT_URL}"
    restart: always
    #volumes:
    #  - "${BACKEND_REPO}:/app"
  frontend:
    container_name: db-list-frontend
    environment:
      VUE_APP_ALERT_URL: "${VUE_APP_ALERT_URL}"
    ports:
      - ${FRONTEND_HOST_PORT}:8080
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${DB_INIT_PATH}:/docker-entrypoint-initdb.d"
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - "discovery.type=single-node"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
networks:
    default:
        name: db-list-net