version: "3.7"

services:
  frontend-nuxt-3:
    ports:
      - ${FRONTEND_HOST_PORT}:3000
  frontend-admin:
    environment:
      DATABASER_BACKEND_ADMIN_URL: "${DATABASER_BACKEND_ADMIN_URL}"
    ports:
      - ${FRONTEND_ADMIN_HOST_PORT}:80
  backend-admin:
    environment:
      DB_PORT: "${DB_PORT}"
      DB_HOST: "${DB_HOST}"
    ports:
      - "${BACKEND_ADMIN_HOST_PORT}:4000"
  backend:
    environment:
      DB_PORT: "${DB_PORT}"
      DB_HOST: "${DB_HOST}"
    ports:
      - "${BACKEND_HOST_PORT}:4000"
