version: '3.7'

services:
  frontend:
    image: docker.ub.gu.se/db-list-frontend:${GIT_REVISION}
    environment:
      DB_LIST_BACKEND_URL: "${DB_LIST_BACKEND_URL}"
      DB_LIST_ALERT_URL: "${DB_LIST_ALERT_URL}"
    ports:
      - ${FRONTEND_HOST_PORT}:80
