version: "3.7"

services:
  frontend-admin:
    image: node:lts-alpine
    command: ["sh", "-c", "npm install && npm run dev"]
    working_dir: /home/node/app
    environment:
      DATABASER_BACKEND_ADMIN_URL: "http://localhost:4010"
    volumes:
      - ../frontend-admin:/home/node/app
    ports:
      - ${FRONTEND_ADMIN_HOST_PORT}:3000
  frontend-nuxt-3:
    command: ["bash", "-c", "yarn install && yarn dev"]
    environment:
      NUXT_API_BASE_URL: ${DATABASER_BACKEND_URL}
    volumes:
      - ../frontend-nuxt-3:/app
    ports:
      - ${FRONTEND_HOST_PORT}:5000
  backend-admin:
    ports:
      - "${BACKEND_ADMIN_HOST_PORT}:4010"
    environment:
      MIX_ENV: dev
      DB_PORT: "${DB_PORT}"
      DB_HOST: "${DB_HOST}"

    volumes:
      - ../backend-admin:/release/backend-admin
    command:
      [
        "sh",
        "-c",
        "mix deps.get && mix deps.compile && mix phx.digest && /usr/local/bin/wait-for-it.sh db:5432 elasticsearch:9200 -t 0 -- mix phx.server",
      ]
  backend:
    ports:
      - "${BACKEND_HOST_PORT}:4000"
    environment:
      MIX_ENV: dev
      DB_PORT: "${DB_PORT}"
      DB_HOST: "${DB_HOST}"
    volumes:
      - ../backend:/release/backend
    command:
      [
        "sh",
        "-c",
        "mix deps.get && mix deps.compile && mix phx.digest && /usr/local/bin/wait-for-it.sh db:5432 elasticsearch:9200 -t 0 -- mix phx.server",
      ]
  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
