version: '3.7'

services:
  db: 
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data/pgdata
  frontend-nuxt-3:
    image: docker.ub.gu.se/db-list-frontend-nuxt-3:${GIT_REVISION}
    environment:
      DB_LIST_BACKEND_URL: "${DB_LIST_BACKEND_URL}"
      DB_LIST_ALERT_URL: "${DB_LIST_ALERT_URL}"
    ports:
      - ${FRONTEND_HOST_PORT}:80
  frontend-admin:
    image: docker.ub.gu.se/db-list-frontend-admin:${GIT_REVISION}
    environment:
      DB_LIST_BACKEND_ADMIN_URL: "${DB_LIST_BACKEND_ADMIN_URL}"
      #DB_LIST_ALERT_URL: "${DB_LIST_ALERT_URL}"
    ports:
      - ${FRONTEND_ADMIN_HOST_PORT}:80