version: '3.7'
services:
  backend:
    restart: always
  backend-admin:
    restart: always
    env_file:
      - secrets.env
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
  db:
    restart: always
  frontend-nuxt:
    restart: always
  frontend-admin:
    restart: always
  elasticsearch:
    restart: always
    volumes:
      - ${ELASTICSEARCH_DATA_PATH}:/usr/share/elasticsearch/data
